"""update table

Revision ID: 0169bbecf122
Revises: 561205f4b531
Create Date: 2024-09-04 13:54:55.640754

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0169bbecf122'
down_revision: Union[str, None] = '561205f4b531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_facebook', sa.Column('link_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('group_facebook', sa.Column('is_member', sa.Boolean(), nullable=True))
    op.add_column('post_facebook', sa.Column('number_of_reaction', sa.Integer(), nullable=True))
    op.add_column('post_facebook', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('post_facebook', 'reaction')
    op.drop_column('post_facebook', 'video')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_facebook', sa.Column('video', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('post_facebook', sa.Column('reaction', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('post_facebook', 'type')
    op.drop_column('post_facebook', 'number_of_reaction')
    op.drop_column('group_facebook', 'is_member')
    op.drop_column('group_facebook', 'link_group')
    # ### end Alembic commands ###
