"""update link group

Revision ID: 082c41a6d029
Revises: 7da2ef75a053
Create Date: 2024-10-18 22:54:32.906039

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '082c41a6d029'
down_revision: Union[str, None] = '7da2ef75a053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'link_group',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'group', ['link_group'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='unique')
    op.alter_column('group', 'link_group',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
