"""update code

Revision ID: 18676765e1f9
Revises: 708dcb0b4d18
Create Date: 2024-09-17 13:28:47.481402

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18676765e1f9'
down_revision: Union[str, None] = '708dcb0b4d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_facebook', 'group_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_facebook', 'group_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
