"""upgrade table

Revision ID: 2781d51b5781
Revises: 48f7c8567103
Create Date: 2024-08-31 13:23:41.490096

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2781d51b5781'
down_revision: Union[str, None] = '48f7c8567103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('images', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages_facebook',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('images', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('receiver_user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('receiver_user_profile', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template_message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('messagesfacebook')
    op.add_column('comment_facebook', sa.Column('onwer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('comment_facebook', sa.Column('onwer_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('comment_facebook', 'sender_name')
    op.drop_column('comment_facebook', 'sender_link')
    op.add_column('post_facebook', sa.Column('link_images', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('post_facebook', sa.Column('link_post', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('post_facebook', sa.Column('owner_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('post_facebook', 'profile_owner_post')
    op.drop_column('post_facebook', 'images')
    op.drop_column('post_facebook', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_facebook', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('post_facebook', sa.Column('images', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('post_facebook', sa.Column('profile_owner_post', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('post_facebook', 'owner_link')
    op.drop_column('post_facebook', 'link_post')
    op.drop_column('post_facebook', 'link_images')
    op.add_column('comment_facebook', sa.Column('sender_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('comment_facebook', sa.Column('sender_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('comment_facebook', 'onwer_link')
    op.drop_column('comment_facebook', 'onwer_name')
    op.create_table('messagesfacebook',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('images', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('receiver_user_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('receiver_user_profile', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='messagesfacebook_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='messagesfacebook_pkey')
    )
    op.drop_table('messages_facebook')
    op.drop_table('template_message')
    # ### end Alembic commands ###
