"""update code

Revision ID: 283ead9a1de1
Revises: 2ba88738a489
Create Date: 2024-08-27 21:48:28.754596

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '283ead9a1de1'
down_revision: Union[str, None] = '2ba88738a489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment_facebook', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('comment_facebook', 'owner_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('comment_facebook', 'note',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('post_facebook', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('post_facebook', sa.Column('post_date', sa.DateTime(), nullable=True))
    op.alter_column('post_facebook', 'owner_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('post_facebook', 'link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('post_facebook', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_facebook', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('post_facebook', 'link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('post_facebook', 'owner_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('post_facebook', 'post_date')
    op.drop_column('post_facebook', 'title')
    op.alter_column('comment_facebook', 'note',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('comment_facebook', 'owner_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('comment_facebook', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
