"""upgrade table

Revision ID: 384e1897e989
Revises: 702e79c0b485
Create Date: 2024-08-31 13:40:09.647249

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384e1897e989'
down_revision: Union[str, None] = '702e79c0b485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment_facebook', 'owner_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment_facebook', 'owner_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
