"""update code

Revision ID: 48f7c8567103
Revises: 0e325653af2a
Create Date: 2024-08-28 11:38:50.981562

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f7c8567103'
down_revision: Union[str, None] = '0e325653af2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_facebook', sa.Column('comment_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment_facebook', 'comment_date')
    # ### end Alembic commands ###
