"""init table

Revision ID: 4a218069e0a3
Revises: 22af437c0393
Create Date: 2024-11-30 13:50:03.843842

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a218069e0a3"
down_revision: Union[str, None] = "22af437c0393"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "accounts", "refresh_token", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "accounts", "access_token", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("accounts", "expires_at", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("accounts", "id_token", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("accounts", "scope", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "accounts", "session_state", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("accounts", "token_type", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "image", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "image", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "accounts", "token_type", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "accounts", "session_state", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("accounts", "scope", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("accounts", "id_token", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "accounts", "expires_at", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "accounts", "access_token", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "accounts", "refresh_token", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
