"""update link group

Revision ID: 4edf6519a4f7
Revises: 082c41a6d029
Create Date: 2024-10-19 13:04:48.446796

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4edf6519a4f7'
down_revision: Union[str, None] = '082c41a6d029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('reaction', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('comments', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('post', 'number_of_reaction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('number_of_reaction', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('post', 'comments')
    op.drop_column('post', 'reaction')
    # ### end Alembic commands ###
