"""update code

Revision ID: 5175c8b29fba
Revises: 0169bbecf122
Create Date: 2024-09-05 19:55:13.649102

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5175c8b29fba'
down_revision: Union[str, None] = '0169bbecf122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_facebook', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('post_facebook', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_facebook', 'deleted')
    op.drop_column('group_facebook', 'deleted')
    # ### end Alembic commands ###
