"""upgrade table

Revision ID: 561205f4b531
Revises: 384e1897e989
Create Date: 2024-08-31 13:47:10.586462

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561205f4b531'
down_revision: Union[str, None] = '384e1897e989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_facebook', sa.Column('sender_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('comment_facebook', sa.Column('sender_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('comment_facebook', 'owner_name')
    op.drop_column('comment_facebook', 'owner_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_facebook', sa.Column('owner_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('comment_facebook', sa.Column('owner_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('comment_facebook', 'sender_link')
    op.drop_column('comment_facebook', 'sender_name')
    # ### end Alembic commands ###
