"""init table

Revision ID: 615532ff221b
Revises: 5740cee66278
Create Date: 2024-11-30 13:33:43.363131

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "615532ff221b"
down_revision: Union[str, None] = "5740cee66278"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("image", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.add_column("users", sa.Column("emailVerified", sa.DateTime(), nullable=False))
    op.drop_column("users", "scopes")
    op.drop_column("users", "is_active")
    op.drop_column("users", "avatar")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("avatar", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column(
            "scopes", postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("users", "emailVerified")
    op.drop_column("users", "image")
    # ### end Alembic commands ###
