"""update column

Revision ID: 8c6bea8110a7
Revises: 6edb0fa707cf
Create Date: 2024-10-13 12:09:14.996874

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8c6bea8110a7"
down_revision: Union[str, None] = "6edb0fa707cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("link_images", sa.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "receiver_user_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "receiver_user_profile", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["template_message.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("messages_facebook")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages_facebook",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("template_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("images", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "receiver_user_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "receiver_user_profile", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("tags", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["template_message.id"],
            name="messages_facebook_template_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="messages_facebook_pkey"),
    )
    op.drop_table("message")
    # ### end Alembic commands ###
