"""update table

Revision ID: 910e2b274391
Revises: 98b4c3b22899
Create Date: 2024-11-17 16:24:28.839834

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '910e2b274391'
down_revision: Union[str, None] = '98b4c3b22899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('group_link_key', 'group', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('group_link_key', 'group', ['link'])
    # ### end Alembic commands ###
