"""update table

Revision ID: d1d579b53549
Revises: 250ddf2fee0c
Create Date: 2024-08-24 18:18:25.516773

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d579b53549'
down_revision: Union[str, None] = '250ddf2fee0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_facebook', sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('group_facebook', 'user_admin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_facebook', 'user_admin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('group_facebook', 'tags')
    # ### end Alembic commands ###
