"""update

Revision ID: d3d88b69205e
Revises: 29c2fe944b20
Create Date: 2024-11-10 00:06:30.503076

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3d88b69205e'
down_revision: Union[str, None] = '29c2fe944b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_scrape', sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history_scrape', 'keyword')
    # ### end Alembic commands ###
