"""update

Revision ID: d43c56723aff
Revises: d899ac744132
Create Date: 2024-11-09 23:27:38.451980

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd43c56723aff'
down_revision: Union[str, None] = 'd899ac744132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('hc_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'group', 'history_scrape', ['hc_id'], ['id'])
    op.drop_column('history_scrape', 'list_group')
    op.drop_column('history_scrape', 'list_post')
    op.add_column('post', sa.Column('hc_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'post', 'history_scrape', ['hc_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'hc_id')
    op.add_column('history_scrape', sa.Column('list_post', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('history_scrape', sa.Column('list_group', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'hc_id')
    # ### end Alembic commands ###
