"""update

Revision ID: d899ac744132
Revises: 830990581859
Create Date: 2024-11-09 22:52:56.419114

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd899ac744132'
down_revision: Union[str, None] = '830990581859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_scrape',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('list_group', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('list_post', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.Enum('GROUP', 'POST', 'START', 'FAILED', 'SUCCESS', name='statusscrape'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_scrape')
    # ### end Alembic commands ###
