"""update

Revision ID: fb81a3129085
Revises: 277a6b9f30ce
Create Date: 2024-11-10 16:08:45.976087

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb81a3129085'
down_revision: Union[str, None] = '277a6b9f30ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


status = sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', name='status_group_scrape')

def upgrade() -> None:
    status.create(op.get_bind())
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('status', status, nullable=True,default='PENDING'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # status.drop(op.get_bind())
    op.drop_column('group', 'status')
    status.drop(op.get_bind())
    # ### end Alembic commands ###
