"""update code

Revision ID: fe7b188233b9
Revises: eb4e8504fec2
Create Date: 2024-09-10 14:05:30.705174

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe7b188233b9'
down_revision: Union[str, None] = 'eb4e8504fec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_facebook_user_id_fkey', 'comment_facebook', type_='foreignkey')
    op.drop_constraint('group_facebook_user_id_fkey', 'group_facebook', type_='foreignkey')
    op.drop_constraint('messages_facebook_user_id_fkey', 'messages_facebook', type_='foreignkey')
    op.drop_constraint('post_facebook_user_id_fkey', 'post_facebook', type_='foreignkey')
    op.alter_column('template_message', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('template_message_user_id_fkey', 'template_message', type_='foreignkey')
    op.add_column('users', sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.create_foreign_key('template_message_user_id_fkey', 'template_message', 'users', ['user_id'], ['id'])
    op.alter_column('template_message', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key('post_facebook_user_id_fkey', 'post_facebook', 'users', ['user_id'], ['id'])
    op.create_foreign_key('messages_facebook_user_id_fkey', 'messages_facebook', 'users', ['user_id'], ['id'])
    op.create_foreign_key('group_facebook_user_id_fkey', 'group_facebook', 'users', ['user_id'], ['id'])
    op.create_foreign_key('comment_facebook_user_id_fkey', 'comment_facebook', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
