services:
  postgres_fb:
    image: postgres:14
    container_name: postgres_fb
    environment:
      POSTGRES_USER: fbtool
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fbtool_db
    ports:
      - "5445:5432"
    volumes:
      - ./postgres_data_fb:/var/lib/postgresql/data
