services:
  postgres_fb:
    image: postgres:14.0
    container_name: postgres_fb
    environment:
      POSTGRES_USER: fbtool
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fbtool_db
    ports:
      - "5445:5432"
    volumes:
      - /Users/nguyenthanhloi/Documents/storage/db_tool_fb_prd:/var/lib/postgresql/data
  
  redis_fb:
    image: redis:latest
    container_name: redis_fb
    ports:
      - "6379:6379"